### ISSUE TITLE
The documentation about installing and configuring crowi is old.

### ISSUE THREAD

**Issue by shinnya** [crowi/crowi#25]
https://github.com/crowi/crowi/blob/master/doc/01-install-and-config.md
The operations described in the doc is old. Do you have any plan to update it?

**Comment by sotarok** [comment]
Thank you for your feedback.

You are right that the documentation in the repository is so old.
I decided that I delete the doc from the repository, and write the documentation in the wiki of the GitHub.
(I wanna move the documentation to the Crowi Demo Site, but I'll carry out it a bit later because the open wiki mode (see some page with anonymous user) has not implemented yet).

Once I moved the content in the doc dir to the wiki in GitHub, I'll update it soon.
https://github.com/crowi/crowi/wiki/Install-and-Configuration

**Comment by shinnya** [comment]
> I tried to move the content in the doc dir to the wiki in GitHub, I'll update it soon.

That's sounds great!
