### ISSUE TITLE
/user/<nonexistent user> page can't be removed

### ISSUE THREAD

**Issue by ogiekako** [crowi/crowi#272]
1. Create /user/foo  from crowi command line tool (https://github.com/b4b4r07/crowi)
2. Open /user/foo from the web
3. The page can't be removed

**Comment by b4b4r07** [comment]
In this case, maybe you should make a ticket at this page: https://github.com/b4b4r07/crowi/issues

**Comment by ogiekako** [comment]
I realized a tricky way to remove the page, so I'm fine now.
1. Move the page to elsewhere like /foo
2. Remove  /foo.

**Comment by b4b4r07** [comment]
Sorry, my bad. This issue was related with Crowi API.

**Comment by sotarok** [comment]
It might be a feature bug.
To fix it, check the user existence if `/user/*` access.
I'll fix it.

**Comment by sotarok** [comment]
I investigated this issue.
Currently, Crowi's behavior is a bit odd.

## Summary

- /user/`{hogehoge}` can be created manually. *1
- After create the user page manually and if the user not exists, alert appears. (And this page can't be deleted. Because user page is not deletable.)
- After that, the user who has `hogehoge` on its username registered, the alert disappears and the looks of the page is actually the user page.
- But, the author of the user page is not the user above but the user who created this page in *1.

## Fix plan

- The user page `/user/hogehoge` should not be created manually. The page direct under `/user` path should only created automatically when the user actually created.

And then,

### How to fix already existing `hogehoge` page

- If the user is not exists, make the page deletable and movable.
- If the user `hogehoge` registered even `/user/hogehoge` already exists by manually, move it to somewhere backup path and create actual user page.

### How to fix the user page already created by others and the user actually exists

- Do nothing. (sorry)
