### ISSUE TITLE
Replace moment to date-fns for shrinking bundle size

### ISSUE THREAD

**Issue by sotarok** [crowi/crowi#473]
Use luxon as datetime library.

**Comment by otofune** [comment]
How about [dayjs](https://github.com/iamkun/dayjs)?

It requires only 2KB footprint (more smaller than luxon). Also it's a drop-in replacement of moment.
See also: https://www.npmtrends.com/dayjs-vs-luxon-vs-moment-vs-date-fns

**Comment by otofune** [comment]
Ah I didn’t notice no tz database (olson or Intl API) support found for dayjs.
If required, we need to write plugin for it.
https://github.com/iamkun/dayjs/issues/46

**Comment by otofune** [comment]
#535

**Comment by otofune** [comment]
I decide to use date-fns instead of luxon. The main purpose of this PR is for #535. date-fns is more small, used library.

https://blog.date-fns.org/post/we-cut-date-fns-v2-minimal-build-size-down-to-300-bytes-and-now-its-the-smallest-date-library-18f2nvh2z0yal
https://www.npmtrends.com/date-fns-vs-luxon-vs-moment

**Comment by otofune** [comment]
Resolved @ #594
